server:
  port: 80
  servlet:
    context-path: /joys

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mvc:
      favicon:
        enabled: true
  datasource:
    name: test
    url: jdbc:mysql://***?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: *
    password: *
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.selffun.joys4fellow.entity  # 注意：对应实体类的路径